信号处理避免不了的是向量运算，numpy是必备品之一。

如下用于导入numpy

In [1]:
import numpy as np


## 1. 数组的初始化


In [2]:
#通常的初始值
#一维数组
a=np.array([1,2,3,4])
b=np.array([1.,2.,3.,4.])
#二维数组
c=np.array([[1.,2.],[3.,4.]])
d=np.array([[1,2],[3,4]],dtype=complex)

print(a,a.dtype)
print(b,b.dtype)
print(c,c.dtype)
print(d,d.dtype)

[1 2 3 4] int32
[1. 2. 3. 4.] float64
[[1. 2.]
 [3. 4.]] float64
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]] complex128


In [3]:
#利用函数进行初始化
np.arange(0,10,1,dtype=float) #arange函数创建

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [4]:
np.ones((3,4),dtype=int) #创建3行4列的全是1的数据

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [5]:
np.zeros((3,4),dtype=float) #创建3行4列的全是0的浮点数

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.linspace(-1,2,31) #起点为-1，终点为2，取31个数（包含两个端点）

array([-1. , -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,
        0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,
        1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ])

In [7]:
np.arange(-1,2,0.1) #起点为-1，步长为0.1，终点小于2，

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01,
        1.00000000e+00,  1.10000000e+00,  1.20000000e+00,  1.30000000e+00,
        1.40000000e+00,  1.50000000e+00,  1.60000000e+00,  1.70000000e+00,
        1.80000000e+00,  1.90000000e+00])

## 2. 数据的更改

In [8]:
#直接对单个数据进行赋值
a = np.arange(0,1,0.1) 
a[8] = 7.3
print( a )

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 7.3 0.9]


In [9]:
a[1:4]=10.0 #批量赋值 从1号到3号，不包括4号
print( a )

[ 0.  10.  10.  10.   0.4  0.5  0.6  0.7  7.3  0.9]


In [10]:
b = a**2  #每一个元素的平方
print(b)

[  0.   100.   100.   100.     0.16   0.25   0.36   0.49  53.29   0.81]


In [11]:
b=[np.sqrt(np.abs(i)) for i in a] #通过a循环遍历赋值
print(b)

[0.0, 3.1622776601683795, 3.1622776601683795, 3.1622776601683795, 0.6324555320336759, 0.7071067811865476, 0.7745966692414834, 0.8366600265340756, 2.701851217221259, 0.9486832980505138]


## 3. 函数运算

In [12]:
## 常用函数，元素级
a=np.array([0,1,2,3])
print(a)


[0 1 2 3]


In [13]:
b = np.sqrt(a)
c = np.exp(a)
d = np.log10(a)
print(b)
print(c)
print(d)

[0.         1.         1.41421356 1.73205081]
[ 1.          2.71828183  7.3890561  20.08553692]
[      -inf 0.         0.30103    0.47712125]


d:\anaconda3\envs\stock\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log10
  This is separate from the ipykernel package so we can avoid doing imports until


In [14]:
## 统计
#均值
a=np.random.randint(0,10,(2,3))
print(a)
print(a.sum(),a.sum(0),a.sum(axis=0)) #分别对矩阵和列求和
print(a.mean(),a.min(1),a.std(1)) #分别对矩阵和行求均值、最小值及标准差
np.median(a) #求中位数


[[5 3 7]
 [0 8 3]]
26 [ 5 11 10] [ 5 11 10]
4.333333333333333 [3 0] [1.63299316 3.29983165]


4.0

In [15]:
## 二维矩阵运算
a=np.array([[1,2],[3,4]])
b=np.arange(6).reshape(2,-1) #生成2行矩阵
print(a,'\n',b)
a.dot(b) #矩阵的乘法

[[1 2]
 [3 4]] 
 [[0 1 2]
 [3 4 5]]


array([[ 6,  9, 12],
       [12, 19, 26]])

# 4. 切片

In [16]:
a=np.arange(0,10,1)**2
print(a)

[ 0  1  4  9 16 25 36 49 64 81]


In [17]:
b = a[3:-2] #切片取值
print(b)


[ 9 16 25 36 49]


In [18]:
c=np.arange(0,20,1).reshape(4,-1)
print(c)
print('第二行：',c[1],'\n二到四列：\n',c[:,1:4],'\n二到四行的第三列',c[1:4,2],
      '\n第二行：',c[1,:])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
第二行： [5 6 7 8 9] 
二到四列：
 [[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]] 
二到四行的第三列 [ 7 12 17] 
第二行： [5 6 7 8 9]


# 5. 形状操作

In [19]:
a=np.random.random((4,3)) #随机产生大小在0-1之间的4行3列的数
a

array([[0.35261262, 0.19412213, 0.76780352],
       [0.03731068, 0.98697434, 0.03781844],
       [0.66644918, 0.2955909 , 0.45633486],
       [0.16569301, 0.86774756, 0.88019716]])

In [20]:
a.shape = (3,4) #改成3行4列
a

array([[0.35261262, 0.19412213, 0.76780352, 0.03731068],
       [0.98697434, 0.03781844, 0.66644918, 0.2955909 ],
       [0.45633486, 0.16569301, 0.86774756, 0.88019716]])

In [21]:
a.shape=(6,-1)
a

array([[0.35261262, 0.19412213],
       [0.76780352, 0.03731068],
       [0.98697434, 0.03781844],
       [0.66644918, 0.2955909 ],
       [0.45633486, 0.16569301],
       [0.86774756, 0.88019716]])

In [22]:
b = a.transpose() #转置
b

array([[0.35261262, 0.76780352, 0.98697434, 0.66644918, 0.45633486,
        0.86774756],
       [0.19412213, 0.03731068, 0.03781844, 0.2955909 , 0.16569301,
        0.88019716]])

# 6.条件判断

In [23]:
a = np.random.random((4,3))
a

array([[0.14624924, 0.1211069 , 0.89362532],
       [0.35890214, 0.16400313, 0.30612201],
       [0.33679027, 0.68496006, 0.44334427],
       [0.02648161, 0.03658537, 0.03506714]])

In [24]:
b = np.where(a>0.5,1,0) # 条件成立时为1，否则为0
b

array([[0, 0, 1],
       [0, 0, 0],
       [0, 1, 0],
       [0, 0, 0]])

# 7.排序

In [25]:
A = np.array([[1, 3, 2, 7],
                    [2, 4, 1, 3],
                    [6, 1, 2, 3]])
print( np.argsort(A) )
print( np.argsort(-A) )

[[0 2 1 3]
 [2 0 3 1]
 [1 2 3 0]]
[[3 1 2 0]
 [1 3 0 2]
 [0 3 2 1]]


In [26]:
import numpy as np 
the_array = np.array([49, 7, 44, 27, 13, 35, 71]) 
sort_array = np.sort(the_array)[::-1]
print(sort_array)

[71 49 44 35 27 13  7]
