In [1]:
a = complex(2, 4)

In [2]:
a

(2+4j)

In [3]:
b = 3 - 5j
b

(3-5j)

In [4]:
a.real

2.0

In [5]:
a.imag

4.0

In [6]:
a.conjugate()

(2-4j)

In [7]:
a + b

(5-1j)

In [8]:
a * b

(26+2j)

In [9]:
a / b

(-0.4117647058823529+0.6470588235294118j)

In [10]:
abs(a)

4.47213595499958

In [11]:
import cmath

In [12]:
cmath.sin(a)

(24.83130584894638-11.356612711218174j)

In [13]:
cmath.cos(a)

(-11.36423470640106-24.814651485634187j)

In [14]:
cmath.exp(a)

(-4.829809383269385-5.5920560936409816j)

In [15]:
import numpy as np

In [16]:
a = np.array([2+3j, 4+5j, 6-7j, 8+9j])
a

array([2.+3.j, 4.+5.j, 6.-7.j, 8.+9.j])

In [17]:
a + 2

array([ 4.+3.j,  6.+5.j,  8.-7.j, 10.+9.j])

In [18]:
a + 4.j

array([2. +7.j, 4. +9.j, 6. -3.j, 8.+13.j])

In [19]:
np.sin(a)

array([   9.15449915  -4.16890696j,  -56.16227422 -48.50245524j,
       -153.20827755-526.47684926j, 4008.42651446-589.49948373j])

In [20]:
c = np.zeros(10, dtype=complex)
c

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j])

In [21]:
d = np.zeros((2,2), dtype=complex)
d

array([[0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]])

In [22]:
d = np.random.random(10) + np.random.random(10) * 1j
d

array([0.79769273+0.26223732j, 0.72983656+0.52070244j,
       0.49914539+0.45237829j, 0.87844675+0.26738883j,
       0.8070637 +0.75923919j, 0.27732103+0.25527304j,
       0.51750846+0.83271874j, 0.63824482+0.92334618j,
       0.0530668 +0.03929325j, 0.2443932 +0.2290962j ])